//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cityLife4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentPhoto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApartmentPhoto()
        {
            this.forDesktop = true;
            this.forMobile = true;
        }
    
        public int Id { get; set; }
        public string filePath { get; set; }
        public PhotoType type { get; set; }
        public OrientationType orientation { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public short sortOrder { get; set; }
        public string thumbnailPath { get; set; }
        public bool forDesktop { get; set; }
        public bool forMobile { get; set; }
    
        public virtual Apartment Apartment { get; set; }
    }
}
