//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cityLife4
{
    using System;
    
    public enum Color : int
    {
        Red = 0,
        Orange = 1,
        Green = 2,
        Blue = 3,
        Gray = 4
    }
}
