//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cityLife4
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeWorkDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeWorkDay()
        {
            this.isSalaryDay = false;
        }
    
        public int Id { get; set; }
        public System.DateTime dateAndTime { get; set; }
        public int hours { get; set; }
        public int salaryCents { get; set; }
        public bool isSalaryDay { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
