//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cityLife4
{
    using System;
    
    public enum expenseType : int
    {
        Salary = 0,
        Booking_Commission = 1,
        Internet_TV = 2,
        Flat_Expenses = 3,
        Cleaning_material = 4,
        Service = 5,
        Remont = 6,
        Bar = 7,
        Linen = 8,
        Parfumery = 9,
        Tooth_Set = 10,
        Coffee_Tea = 11
    }
}
