//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cityLife4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int Id { get; set; }
        public System.DateTime date { get; set; }
        public int amount { get; set; }
        public string currency_currencyCode { get; set; }
        public string description { get; set; }
        public int expenseType_Id { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual ExpenseType ExpenseType { get; set; }
    }
}
