//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cityLife4
{
    using System;
    
    public enum OrderStatus : int
    {
        Created = 0,
        CheckedIn = 1,
        CheckedOut = 2,
        Cancelled = 3,
        Free = 9
    }
}
