//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cityLife4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.childrenCount = 0;
            this.confirmationNumber = "0";
            this.ApartmentDays = new HashSet<ApartmentDay>();
        }
    
        public int Id { get; set; }
        public System.DateTime checkinDate { get; set; }
        public System.DateTime checkoutDate { get; set; }
        public int dayCount { get; set; }
        public int adultCount { get; set; }
        public int childrenCount { get; set; }
        public string expectedArrival { get; set; }
        public string specialRequest { get; set; }
        public OrderStatus status { get; set; }
        public string confirmationNumber { get; set; }
        public string cancellationNumber { get; set; }
        public int price { get; set; }
        public int amountPaid { get; set; }
        public string bookedBy { get; set; }
        public Color OrderColor { get; set; }
        public string staffComments { get; set; }
    
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApartmentDay> ApartmentDays { get; set; }
        public virtual Apartment Apartment { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
