//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cityLife
{
    using System;
    
    public enum PhotoType : short
    {
        Main = 0,
        Additional = 1,
        Thumbnail = 2
    }
}
