//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cityLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pricing
    {
        public int Id { get; set; }
        public short adults { get; set; }
        public short children { get; set; }
        public int priceWeekDay { get; set; }
        public int priceWeekEnd { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
