//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cityLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitTest
    {
        public string series { get; set; }
        public int number { get; set; }
        public string expectedResult { get; set; }
        public string actualResult { get; set; }
        public System.DateTime dateLastRun { get; set; }
        public Nullable<bool> correctFlag { get; set; }
    }
}
